### ISSUE TITLE
Programming related issues

### ISSUE THREAD

**Issue by withinboredom** [guifarias31/msfs_tbm930_project#10]
I was reading [the forum](https://forums.flightsimulator.com/t/tbm-930-mod-torque-exterior-lights-dimmable-displays-lower-brightnes-on-standby-instrument-and-gear-drag/280592/12) and I noticed that you could use some programming help. I'm a software engineer but not a pilot (though I love sims and flying) and happy to help. I'm just wondering if you can create some issues or list out here what you need programming-wise and I'd love to help out. I usually fly the SF-50 Vision Jet in X-Plane, and I've now fallen in love with the TBM in FS2020

**Comment by guifarias31** [comment]
Hi! Nice to hear that, please contact me on Discord: Guilherme Farias#9971

**Comment by withinboredom** [comment]
Which discord? I'm not quite up to speed on the community yet :)

**Comment by withinboredom** [comment]
Sent friend request 🤦
