### ISSUE TITLE
Upper light some times blink when installed mod

### ISSUE THREAD

**Issue by mixMugz** [guifarias31/msfs_tbm930_project#13]
Upper cabin light FO sometimes blink (when it off of course) after installed mod.

**Comment by guifarias31** [comment]
Sorry, I didn't understand. Could you send me a screenshot or video to show what's going on?

**Comment by mixMugz** [comment]
![image](https://user-images.githubusercontent.com/17923916/95058493-4ab98a00-0700-11eb-8f67-2a6de9d82fb8.png)
This lamp sometimes blink one/two times. May be it's not mod problem. Removed mod, installed again. Now didnt see this issue.

**Comment by mixMugz** [comment]
Didnt see anymore
