### ISSUE TITLE
Can't seem to make this work

### ISSUE THREAD

**Issue by mikebakke** [guifarias31/msfs_tbm930_project#16]
If I understand correctly -
1. Installation is to copy the unzipped dir into community
2. The audible minimums are included
3. This should work fine with any other mod (ie. liveries) which don't contain panel.xml for the TBM

Despite this - I set a minimum for (say) 100' and specify RA to avoid baro offsets but I never hear any audible altitude callouts when landing. 

I am on a Steam install with a bespoke install dir (d:\msfs) instead of the default MS one. There is also a MS default hierarchy on C;\user\appdata.... but I put all my other (working) mods into the d:\msfs\community and it's fine. I did try this one in the c:\ folder but nada. 

I'm pretty certain the mod is loaded because I don't think I get the SEP alert in CAS when switched on. All my volumes other than music are 100% and on some planes I get the 500' callout but never the TBM.

Any thoughts on what I can try?

Any way to put an "eyecatch" in the mod so that I can confirm at a glance that the mod itself is loaded? Like a piece of text on the panel? 

Many thanks

Mike (@b3lt3r on forum/discord)

**Comment by kaerbr** [comment]
For me the "minimum warning" is very quiet. So take a "closer look". (:

**Comment by mikebakke** [comment]
ok. Solved... My go-to livery for the TBM includes a panel for some reason. Tried deleting that but ended up with blank Garmins :-) so I've asked the livery author if it's required or not.

It now works fine with default plane and my other livery, and yes, the alert for minimums is quiet but happens. 

Thanks!

**Comment by kaerbr** [comment]
good to hear.
if all is fixed please close the issue. (:
![grafik](https://user-images.githubusercontent.com/70379879/95379514-c3c60680-08e5-11eb-8102-24ab3af97ad5.png)

**Comment by PharaohSteve** [comment]
Can you advise what livery this was occurring on before closing the issue?

**Comment by mikebakke** [comment]
The livery which appears to clash is the carbon-gold TBM - from here: https://flightsim.to/file/555/tbm-930-carbon-gold-4k-2k
Rgds
