### ISSUE TITLE
Adaption to MSFS version 1.9.5.0

### ISSUE THREAD

**Issue by sfdeham** [guifarias31/msfs_tbm930_project#20]
A new version of MSFS has just been released as per https://forums.flightsimulator.com/t/news-release-notes-update-4-1-9-5-0-now-available/300498

Kindly check and advice if an update to your project is required.

**Comment by guifarias31** [comment]
I did that [5 hours ago](https://github.com/guifarias31/msfs_tbm930_project/commit/70f18990433e0b776194cdbeefbb12c7b0ecc24e). I don't think this update will brake anything, but I updated manifest.json just in case. If you encounter any issues, just redownload the mod. No TBM 930 files were modified in this update.
