### ISSUE TITLE
Please include G3000 mods

### ISSUE THREAD

**Issue by odessadraekavik** [guifarias31/msfs_tbm930_project#21]
Why not including the G3000 mod bellow by default ?

G3000 Modification
https://github.com/Working-Title-MSFS-Mods/fspackages/releases/tag/g3000-v0.2.0-pre1

Best regards

**Comment by odessadraekavik** [comment]
![image](https://user-images.githubusercontent.com/4887819/96061909-a6b8a700-0e94-11eb-86bc-6b0184a74f47.png)

**Comment by odessadraekavik** [comment]
![image](https://user-images.githubusercontent.com/4887819/96061965-c3ed7580-0e94-11eb-88eb-6d4ec3111c37.png)

**Comment by odessadraekavik** [comment]
![image](https://user-images.githubusercontent.com/4887819/96061997-d9fb3600-0e94-11eb-97bb-57403645af8a.png)

**Comment by guifarias31** [comment]
Why should I include? It's a separate project and works great separately.

**Comment by odessadraekavik** [comment]
Well you included UWA's light mod.
But I understand :)

**Comment by guifarias31** [comment]
> Well you included UWA's light mod.

It's because Uwa's mod shares a file I have edited (systems.cfg), and it would conflict if I doesn't.

**Comment by odessadraekavik** [comment]
Hah, understood !

Thanks **a lot** for the time you put in this project, giving some love to the TBM!
