### ISSUE TITLE
CTD after last MSFS update

### ISSUE THREAD

**Issue by kutak11** [guifarias31/msfs_tbm930_project#26]
just noticed very often CTD with this mod after last MSFS update...  
during flight on cruise level MSFS just stopped working, after removing from comunity folder it didnt happen

**Comment by guifarias31** [comment]
Hi there!
I didn't have much time today to make the mod work on the latest update. I just released 0.5.4 Beta as a hotfix, and tomorrow I'll have a closer look on "TBM930_interior.xml" file.

**Comment by kutak11** [comment]
not 100% sure now that this causes this mod... I have now CTD also with community folder empty, sorry

**Comment by guifarias31** [comment]
Yeah, looks like it's not caused by the mod: https://www.facebook.com/MIcrosoftFlightSimulatorOfficial/posts/385102199531877
