### ISSUE TITLE
Pedestal light?

### ISSUE THREAD

**Issue by mixMugz** [guifarias31/msfs_tbm930_project#28]
How to turn off pedestal light when panel lights is on?

**Comment by guifarias31** [comment]
I think it's that way. You most often turn on / down the panel brightness at night, and that's why it turns pedestal light on.
My mod has nothing to do with this.

**Comment by mixMugz** [comment]
But i need panel light, but not need pedestal light.
Can you change it to cabin/salon light switch?

**Comment by guifarias31** [comment]
As I said, it's probably this way on the real plane, and makes a lot of sense. Even if I could change (which I can't, because I'm not a programmer), I wouldn't, because my mod aims for most realism.

**Comment by mixMugz** [comment]
So. May be you can tell me how it change or remove. For my plane?

**Comment by guifarias31** [comment]
> (which I can't, because I'm not a programmer)

As I said, I don't know how to do this.

**Comment by mixMugz** [comment]
So. I found where is it.
There is need to change in system.cfg.
`lightdef.23 = Type:11#Index:0#LocalPosition:-14.76,0,3.35#LocalRotation:80,0,0#EffectFile:LIGHT_ASOBO_CockpitSpotNarrow#PotentiometerIndex:5`
Also change in 
`			<UseTemplate Name="ASOBO_LIGHTING_Pedestal_Emissive_Template">
				<POTENTIOMETER>5</POTENTIOMETER>
				<NODE_ID>light_pedestal</NODE_ID>
			</UseTemplate>
`
Now Pedestal light work when turn Cabin switch on.

**Comment by mixMugz** [comment]
Second part missed file name: model\TBM930_interior.xml
In this file definition for LIT textures for every system in plane
