### ISSUE TITLE
G3000 Lighting adjustment INOP

### ISSUE THREAD

**Issue by Andydigital** [guifarias31/msfs_tbm930_project#3]
Hi the adjustable G3000 backlighting with the Panel lighting POT on the overhead doesn't work for me, I don't think it ever has since the merge into your package. The standalone one from [https://github.com/Uwajimaya/FS2020](url) worked fine for me in the past.

**Comment by Andydigital** [comment]
I've just updated to the latest version you released last night and the PFD adjustment is working but the MFD not.

**Comment by guifarias31** [comment]
Hi. The one you linked is the Uwa's light fix, not the [dimmable G3000 from kaosfere](https://github.com/kaosfere/msfs-fixes/tree/master/fixes/tbm930_lighting_fix). I'll have a look on the G3000 ajustable lights, thanks for reporting.

**Comment by guifarias31** [comment]
Just fixed that, thanks. 0.4.9b hotfix coming in a few minutes.
