### ISSUE TITLE
Lighting mod

### ISSUE THREAD

**Issue by mixMugz** [guifarias31/msfs_tbm930_project#32]
My little lighting mod.
What i done.
1. Panel light knob always on (for identity in darknes)
2. Panel light knob day start at zero (old at 100%).
3. Panel light knob 100% - max light (instead turn off) - need to understand how it work in real plane
4. ELT button always on
5. ELT text mapped to panel light
6. Pedestal light map to access light button
7. Reworked all ambient light. (only G3000 still in process)

video: https://youtu.be/h4vmkpaieeE

**Comment by mixMugz** [comment]
Yes! I did it!!!
Screen ambient light work with Workingtitle 3000 mod.

There is minimal PFD light:
![image](https://user-images.githubusercontent.com/17923916/98481379-e1e79500-220a-11eb-8c0b-0fe141b0a0e0.png)

There is maximum PFD light:
![image](https://user-images.githubusercontent.com/17923916/98481385-f0ce4780-220a-11eb-9776-51d9e37fec0f.png)

**Comment by mixMugz** [comment]
So how i can send you code?

**Comment by mixMugz** [comment]
There is archive with moded files.
https://www.hdz.ru/tbm930-improvement.7z

You can test and include everything what you like in the mod.

What files is changed:
- layout.json (added some fx files and renamed one)
- \Effects\* - rename one file and added new files
- TBM930_interior.xml - added lightings
- systems.cfg - changed lightings

**Comment by mixMugz** [comment]
@guifarias31 can you test it and include to mod?

**Comment by leppie** [comment]
@mixMugz It is probably best to create a PR. That is the normal way of code submissions on Github. 

Basic steps would be:
- clone this repo
- check it out out on your pc
- copy your files over it and commit the changes
- push changes back to your clone

Github from there will guide you IIRC.

**Comment by mixMugz** [comment]
> @mixMugz It is probably best to create a PR. That is the normal way of code submissions on Github.
> 
> Basic steps would be:
> 
> * clone this repo
> * check it out out on your pc
> * copy your files over it and commit the changes
> * push changes back to your clone
> 
> Github from there will guide you IIRC.

done

**Comment by mixMugz** [comment]
Merged
