### ISSUE TITLE
Glideslope following issue?

### ISSUE THREAD

**Issue by e4rthdog** [guifarias31/msfs_tbm930_project#33]
Today in 2 flights during ILS, i noticed that the plane captured LOC and GS normally but as time passed by , the plane increased VS and after a while it was well below GS.

I tried to disengage and engage the AP with no luck.

Is this something known? Could it be coming from the Working title G3000 mod?

Thanks.

**Comment by pstengel** [comment]
When I've encountered this in the past, I sped the plane up a bit, and it recovered. It seems to be very sensitive to the throttle/speed, and you'll sink under the GS if you don't give it enough power.

**Comment by Snapli** [comment]
Isn't this one of the known issues MS/Asobo disclosed in one of their latest development updates and that it affects all planes...?

**Comment by e4rthdog** [comment]
> Isn't this one of the known issues MS/Asobo disclosed in one of their latest development updates and that it affects all planes...?

I did not know that, but i never had such problem with TBM or CJ4/A320, so i thought that it is something new.

**Comment by guifarias31** [comment]
I think this is a Vanilla issue, not something related to the mod itself.
