### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by valeriosouza** [guifarias31/msfs_tbm930_project#39]
Hello, I'm also a Brazilian and I'm trying to contact you, how can I?

**Comment by guifarias31** [comment]
Opa
O projeto foi descontinuado, por que precisei me mudar e deixei o computador, estou sem.
O mixMugz decidiu continuar o projeto: https://github.com/mixMugz/msfs_tbm930_project
Se quiser entrar em contato comigo, me chama no Discord: [Guilherme Farias#9971](https://discordapp.com/channels/@me/207215431654572032)
