### ISSUE TITLE
[Suggestion] Please add commit messages when making changes!

### ISSUE THREAD

**Issue by DuckBoss** [guifarias31/msfs_tbm930_project#7]
Hello!

I've been following this project since the start, and one thing I (as well as many active github users) would appreciate is
adding commit messages when you make a commit to the repository.
By doing so, it will make it a lot easier for people to see exactly what changes you have made (and for what purpose).
For example, this commit: [0.4.13b commit](https://github.com/guifarias31/msfs_tbm930_project/commit/7506b5c4da0233f8150eba665a9246cae144d637) doesn't say why the changes in the files were made.

Adding commit messages will also help you a lot when you update the README to include recent changes/updates.

**Comment by guifarias31** [comment]
Hi. Github is a new thing for me, and I don't know how to use it properly.
Everything that is not default is listed on the README.md file, comparing to the default values. 
I'm posting the "changelog" on the releases page:
![image](https://user-images.githubusercontent.com/70555403/94744400-49c6d800-034f-11eb-9edc-136cea8966a8.png)
I don't even know what means "commit messages", sorry! lol

**Comment by DuckBoss** [comment]
Ah that's completely fine!
Commit messages are a useful way to keep track of the changes to files you are making in the repository.
So, when you commit changes to your repository you have an option to add a message to it.

Here's an example picture of how the commit history looks with commit messages (from one of my repositories):
| Example Commit History | Your Commit History |
| ----------------------------|----------------------- |
| ![image](https://user-images.githubusercontent.com/20238115/94751575-138d5680-0357-11eb-8cd8-d9bdf9204336.png) | ![image](https://user-images.githubusercontent.com/20238115/94752049-1b99c600-0358-11eb-89cd-4b822787efef.png) |

If this project becomes bigger over time, I'm sure learning this will be helpful!
It will also serve as a quick reference when you are updating your changelogs or readme files.
<hr>

#### I'll close this issue, since I only wanted to bring this Github feature to your attention.
